added Asked by Open AI no. 366
ruppysuppy/Daily-Coding-Problem-Solutions pull request #8
Opened 2023-01-25 18:03 UTC by Almoeeni

2023-01-26 02:53 UTC, ruppysuppy requested changes
The repo follows [black convention](https://pypi.org/project/black/), so make sure it's formatted properly.

I would be travelling for the next 5 days, so I might be slow to respond

2023-01-26 02:53 UTC, ruppysuppy commented on Solutions/366.py
> +    print("false")
Not indented

2023-01-26 02:53 UTC, ruppysuppy commented on Solutions/366.py
> +# DO NOT CHANGE the code below, we use it to grade your submission. If changed your submission will be failed
stray comments

2023-01-26 04:23 UTC, Almoeeni commented on Solutions/366.py
> +# DO NOT CHANGE the code below, we use it to grade your submission. If changed your submission will be failed
> stray comments

I fix these issues highlighted by you.

2023-02-01 03:48 UTC, ruppysuppy commented
Thanks for making the changes, but from [here](https://github.com/dhanendraverma/Daily-Coding-Problem#problem-366) it seems like the problem is completely different?

2023-02-01 09:32 UTC, Almoeeni commented
> Thanks for making the changes, but from [here](https://github.com/dhanendraverma/Daily-Coding-Problem#problem-366) it seems like the problem is completely different?

Can you please elaborate me please. you mentioned different repo instead of [this](https://github.com/ruppysuppy/Daily-Coding-Problem-Solutions)

2023-02-01 10:02 UTC, ruppysuppy commented
As in the PR is pretty much ready to be merged, but are you sure that the problem you shared is the Daily Coding Problem 366?

2023-02-01 10:16 UTC, Almoeeni commented
> As in the PR is pretty much ready to be merged, but are you sure that the problem you shared is the Daily Coding Problem 366?

I know that it's going to be 1 day up from 365 day but the main thing is that it's from Open AI and the repo is purely python based solutions, So that's why i'm contributing to it.

2023-02-01 15:49 UTC, merged